In [2]:
import numpy as np
import random
import numpy.ma as ma

a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

all(all(x == [1, 2, 3]) or all(x == [4, 5, 6]) for x in a)


False

In [8]:
a = np.ndarray.tolist(np.array([[1, 2], [2, 2], [3, 2]]))

b = np.array([[1, 2, 3], [2, 2, 3], [3, 2, 3], [1, 0, 0], [2, 1, 3]])

b_init = np.ndarray.tolist(b.copy())
size_of_dataset = len(b_init)

n_clusters = 2
centroids = np.zeros((n_clusters, 3))

number_of_centroids_chosen = 0
for i in range(size_of_dataset):
    random.shuffle(b_init)
    cand_centr = b_init.pop()
    if all([lambda x: not all(x)([cand_centr[i] == x[i] for i in len(x)]) for x in centroids]):
        centroids[number_of_centroids_chosen] = cand_centr
        number_of_centroids_chosen += 1
    
    if number_of_centroids_chosen == n_clusters:
        break

if number_of_centroids_chosen < n_clusters:
    print("There appears to be less different data points than clusters")

else:
    print(centroids)


[[3. 2. 3.]
 [1. 2. 3.]]


In [9]:
a = np.array([[1, 3], [1, 4], [1, 5]])
b = zip(a, range(3))
print(list(b))

[(array([1, 3]), 0), (array([1, 4]), 1), (array([1, 5]), 2)]


In [14]:
mask = np.array([0, 0, 0, 1, 0])
a = np.array([1, 2, 3, 4, 5])
a*mask

array([0, 0, 0, 4, 0])

In [10]:

a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
np.mean(ma.masked_where(a != a, a), axis=0)

masked_array(data=[4., 5., 6.],
             mask=False,
       fill_value=1e+20)

In [75]:
np.allclose([[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]], atol = 1)

True