In [65]:
import numpy as np

inp = input().split()

pi = np.array(list(map(float, inp[:2])))

O = np.array(list(map(int, [*inp[10]])))

A = np.array([[float(inp[2]), float(inp[3])],\
              [float(inp[4]), float(inp[5])]])

B = np.array([[float(inp[6]),float(inp[7])],\
              [float(inp[8]),float(inp[9])]])

print(pi)
print(O)
print(A)
print(B)
print('=====================\n \n=====================')

def forward_backward_2(A, B, pi, O):

    T = len(O)
    N = 2
    
    a = np.zeros((2, T))
    a[:, 0] = [pi[j]*B[j,O[0]] for j in range(N)]
    for t in range(1, T):
        for j in range(2):
            a[j, t] = sum(a[i, t-1]*A[i, j]*B[j, O[t]] for i in range(N))
            
    print(a.T)
    print('++++++++++++++++')

    b = np.zeros((2, T))
    b[:, T-1] = [1, 1]
    for t in range(T-1)[::-1]:
        for i in range(2):
            b[i, t] = sum(A[i, j]*B[j,O[t+1]]*b[j, t+1] for i in range(N)) 
            
    print(b.T)
    print('++++++++++++++++')

    P = np.zeros((2, T))
    for t in range(T):
        for j in range(2):
            P[j, t] = (a[j, t]*b[j, t])/sum([a[i, T-1] for i in range(N)])
            
    return P.T


print(forward_backward_2(A, B, pi, O))



0.5 0.5 0.8 0.2 0.2 0.8 0.5 0.5 0.1 0.9 01010100111111111100000000
[0.5 0.5]
[0 1 0 1 0 1 0 0 1 1 1 1 1 1 1 1 1 1 0 0 0 0 0 0 0 0]
[[0.8 0.2]
 [0.2 0.8]]
[[0.5 0.5]
 [0.1 0.9]]
 
[[2.50000000e-01 5.00000000e-02]
 [1.05000000e-01 8.10000000e-02]
 [5.01000000e-02 8.58000000e-03]
 [2.08980000e-02 1.51956000e-02]
 [9.87876000e-03 1.63360800e-03]
 [4.11486480e-03 2.95437456e-03]
 [1.94138338e-03 3.18647261e-04]
 [8.08418076e-04 6.43194484e-05]
 [3.29799175e-04 1.91825257e-04]
 [1.51102196e-04 1.97478036e-04]
 [8.01886820e-05 1.69382581e-04]
 [4.90137309e-05 1.36389421e-04]
 [3.32444345e-05 1.07022855e-04]
 [2.40000593e-05 8.30404538e-05]
 [1.79040691e-05 6.41091374e-05]
 [1.35725414e-05 4.93813114e-05]
 [1.03671477e-05 3.79976016e-05]
 [7.94661924e-06 2.92243598e-05]
 [6.10108367e-06 2.49688117e-06]
 [2.69012158e-06 3.21772167e-07]
 [1.10822585e-06 7.95442050e-08]
 [4.51244761e-07 2.85280534e-08]
 [1.83350710e-07 1.13071395e-08]
 [7.44709978e-08 4.57158535e-09]
 [3.02455577e-08 1.85514678e-

In [61]:
d = lambda x: 1 if x == 1 else x*d(x-1)
print(f'5!={d(5)}')
f = lambda x: ''.join(list(map(lambda y: {'0':'1', '1':'0'}[y], x)))
print(f('111000'))

g = lambda x: {d:f, f:d}[x]

g(f)(5)

def karry(f):
    return lambda x, y: f(x) 

def xx(f, g):
    return lambda x, y: (f(x), g(y))

xx(d, f)(5, '0011')

K = lambda f: lambda x: map(f, x)

list(K(f)(['1100','101011','0011']))





5!=120
000111


['0011', '010100', '1100']